author: Dannii Willis
description: "Linguist & Theologian"
email: curiousdannii@gmail.com
encoding: UTF-8
future: true
gfm_quirks: paragraph_end
github: [metadata]
github_username: curiousdannii
jailed: false
kramdown:
  input: GFM
  hard_wrap: false
theme: jekyll-theme-tactile
title: Dannii Willis